version: '2'

services:
#postgres é o banco de dados
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

#redis é o banco de dados de fila para enviar os emails
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

#jobs é o que vai rodar efetivamente o reddis e faz tudo acontecer
  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/storeadmin'
    volumes_from:
      - box

#APP é onde vai subir o nosso projeto
  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/petadmin'
    volumes_from:
    - box

#Box é onde deixa as GEMs caceadas, é onde voce deixa os arquivos, ele é somente uma pasta
  box:
    image: busybox
    volumes:
      - /box

#Mailcatcher vai subir e interceptar os emails. Permitindo que a gente veja os emails no meio da caminho.
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1025:25
      - 1080:80

volumes:
  redis:
  postgres:
  box: